//
//  GameCenterCategories.h
//  PeterPogHalloween
//
//  Created by Shu Chiun Cheah on 10/24/11.
//  Copyright (c) 2011 GeoloPigs. All rights reserved.
//

#import <Foundation/Foundation.h>

// score categories
extern NSString* const GAMECENTER_CATEGORY_HIGHSCORE;
extern NSString* const GAMECENTER_CATEGORY_PIGGYBANK;
//extern NSString* const GAMECENTER_CATEGORY_TOURNEYHIGH;
//extern NSString* const GAMECENTER_CATEGORY_TOURNEYWINS;

// achievement ids
extern NSString* const GAMECENTER_ACHIEVEMENT_MULTX3;
extern NSString* const GAMECENTER_ACHIEVEMENT_MULTX10;
extern NSString* const GAMECENTER_ACHIEVEMENT_MULTX20;
extern NSString* const GAMECENTER_ACHIEVEMENT_MAXMISSILES;
extern NSString* const GAMECENTER_ACHIEVEMENT_MAXGUNS;
extern NSString* const GAMECENTER_ACHIEVEMENT_500WATERBOARS;
extern NSString* const GAMECENTER_ACHIEVEMENT_500LANDBOARS;
extern NSString* const GAMECENTER_ACHIEVEMENT_500AIRBOARS;
extern NSString* const GAMECENTER_ACHIEVEMENT_8ROUTES;
extern NSString* const GAMECENTER_ACHIEVEMENT_6ROUTES;
extern NSString* const GAMECENTER_ACHIEVEMENT_3ROUTES;
extern NSString* const GAMECENTER_ACHIEVEMENT_250k;
extern NSString* const GAMECENTER_ACHIEVEMENT_500k;
extern NSString* const GAMECENTER_ACHIEVEMENT_1M;
extern NSString* const GAMECENTER_ACHIEVEMENT_BLIMP;
extern NSString* const GAMECENTER_ACHIEVEMENT_SUB;
extern NSString* const GAMECENTER_ACHIEVEMENT_PUMPKIN;
extern NSString* const GAMECENTER_ACHIEVEMENT_ROUTE1A;
extern NSString* const GAMECENTER_ACHIEVEMENT_ROUTE2A;
extern NSString* const GAMECENTER_ACHIEVEMENT_ROUTE3A;
extern NSString* const GAMECENTER_ACHIEVEMENT_ROUTE4A;
extern NSString* const GAMECENTER_ACHIEVEMENT_ROUTE5A;
extern NSString* const GAMECENTER_ACHIEVEMENT_ROUTE6A;
extern NSString* const GAMECENTER_ACHIEVEMENT_ROUTE7A;
extern NSString* const GAMECENTER_ACHIEVEMENT_ROUTE8A;
extern NSString* const GAMECENTER_ACHIEVEMENT_ROUTE9A;
extern NSString* const GAMECENTER_ACHIEVEMENT_ROUTE10A;
extern NSString* const GAMECENTER_ACHIEVEMENT_ACE;
extern NSString* const GAMECENTER_ACHIEVEMENT_FULLHEALTH;
extern NSString* const GAMECENTER_ACHIEVEMENT_10CARGOS;
extern NSString* const GAMECENTER_ACHIEVEMENT_50CARGOS;
extern NSString* const GAMECENTER_ACHIEVEMENT_100CARGOS;
extern NSString* const GAMECENTER_ACHIEVEMENT_30MINS;
extern NSString* const GAMECENTER_ACHIEVEMENT_100MINS;
extern NSString* const GAMECENTER_ACHIEVEMENT_300MINS;
//extern NSString* const GAMECENTER_ACHIEVEMENT_1TOURNEYWIN;
extern NSString* const GAMECENTER_ACHIEVEMENT_POGWING1ROUTE;
extern NSString* const GAMECENTER_ACHIEVEMENT_POGRANG1ROUTE;
extern NSString* const GAMECENTER_ACHIEVEMENT_POGWINGMAX;
extern NSString* const GAMECENTER_ACHIEVEMENT_POGRANGMAX;
extern NSString* const GAMECENTER_ACHIEVEMENT_HOVER;
extern NSString* const GAMECENTER_ACHIEVEMENT_UNLOCKROUTE2;
extern NSString* const GAMECENTER_ACHIEVEMENT_UNLOCKROUTE3;
extern NSString* const GAMECENTER_ACHIEVEMENT_UNLOCKROUTE4;
extern NSString* const GAMECENTER_ACHIEVEMENT_UNLOCKROUTE5;
extern NSString* const GAMECENTER_ACHIEVEMENT_UNLOCKROUTE6;
extern NSString* const GAMECENTER_ACHIEVEMENT_UNLOCKROUTE7;
extern NSString* const GAMECENTER_ACHIEVEMENT_UNLOCKROUTE8;
extern NSString* const GAMECENTER_ACHIEVEMENT_UNLOCKROUTE9;
extern NSString* const GAMECENTER_ACHIEVEMENT_UNLOCKROUTE10;
extern NSString* const ACHIEVEMENT_POGWINGIAP;
extern NSString* const ACHIEVEMENT_POGRANGIAP;

// game goals
extern NSString* const GAME_GOAL_ROUTE1;
extern NSString* const GAME_GOAL_ROUTE2;
extern NSString* const GAME_GOAL_ROUTE3;

// only used internally to keep the score report file non-empty
extern NSString* const GAMECENTER_INTERNAL_APPNAME;

