//
//  GimmieEventIds.h
//  PeterPog
//
//  Created by Shu Chiun Cheah on 3/19/12.
//  Copyright (c) 2012 GeoloPigs. All rights reserved.
//

#import <Foundation/Foundation.h>

extern NSString* GIMMIE_EVENTID_MULTX3;
extern NSString* GIMMIE_EVENTID_MULTX10;
extern NSString* GIMMIE_EVENTID_MULTX20;
extern NSString* GIMMIE_EVENTID_WEAPONMAX;
extern NSString* GIMMIE_EVENTID_WATERBOAR;
extern NSString* GIMMIE_EVENTID_LANDBOAR;
extern NSString* GIMMIE_EVENTID_AIRBOAR;
extern NSString* GIMMIE_EVENTID_BLIMP;
extern NSString* GIMMIE_EVENTID_SUB;
extern NSString* GIMMIE_EVENTID_PUMPKIN;
extern NSString* GIMMIE_EVENTID_HOVER;
extern NSString* GIMMIE_EVENTID_TRAINEECOURIER;
extern NSString* GIMMIE_EVENTID_SEMIPROCOURIER;
extern NSString* GIMMIE_EVENTID_PROCOURIER;
extern NSString* GIMMIE_EVENTID_250K;
extern NSString* GIMMIE_EVENTID_500K;
extern NSString* GIMMIE_EVENTID_1M;
extern NSString* GIMMIE_EVENTID_COURIERDUDE;
extern NSString* GIMMIE_EVENTID_COURIERMINIMARATHON;
extern NSString* GIMMIE_EVENTID_COURIERMARATHON;
extern NSString* GIMMIE_EVENTID_ROUTE1EXPERT;
extern NSString* GIMMIE_EVENTID_ROUTE2EXPERT;
extern NSString* GIMMIE_EVENTID_ROUTE3EXPERT;
extern NSString* GIMMIE_EVENTID_ROUTE4EXPERT;
extern NSString* GIMMIE_EVENTID_ROUTE5EXPERT;
extern NSString* GIMMIE_EVENTID_ROUTE6EXPERT;
extern NSString* GIMMIE_EVENTID_ROUTE7EXPERT;
extern NSString* GIMMIE_EVENTID_ROUTE8EXPERT;
extern NSString* GIMMIE_EVENTID_ROUTE9EXPERT;
extern NSString* GIMMIE_EVENTID_ROUTE10EXPERT;
extern NSString* GIMMIE_EVENTID_SUPERPOG;
extern NSString* GIMMIE_EVENTID_SCRATCHFREE;
extern NSString* GIMMIE_EVENTID_TRAINEEPILOT;
extern NSString* GIMMIE_EVENTID_AMATEURPILOT;
extern NSString* GIMMIE_EVENTID_PROPILOT;
extern NSString* GIMMIE_EVENTID_WINTOURNEY;
extern NSString* GIMMIE_EVENTID_POGWINGROUTE;
extern NSString* GIMMIE_EVENTID_POGRANGROUTE;
extern NSString* GIMMIE_EVENTID_POGWINGMAX;
extern NSString* GIMMIE_EVENTID_POGRANGMAX;
extern NSString* GIMMIE_EVENTID_POGWINGIAP;
extern NSString* GIMMIE_EVENTID_POGRANGIAP;
extern NSString* GIMMIE_EVENTID_POGCOINSSTARTERPACK;
extern NSString* GIMMIE_EVENTID_POGCOINSCOURIERPACK;
extern NSString* GIMMIE_EVENTID_POGCOINS100KPACK;
extern NSString* GIMMIE_EVENTID_PLAY3JOURNEYS;
extern NSString* GIMMIE_EVENTID_PLAYWITHFRIENDS;
extern NSString* GIMMIE_EVENTID_UNLOCKROUTE2;
extern NSString* GIMMIE_EVENTID_UNLOCKROUTE3;
extern NSString* GIMMIE_EVENTID_UNLOCKROUTE4;
extern NSString* GIMMIE_EVENTID_UNLOCKROUTE5;
extern NSString* GIMMIE_EVENTID_UNLOCKROUTE6;
extern NSString* GIMMIE_EVENTID_UNLOCKROUTE7;
extern NSString* GIMMIE_EVENTID_UNLOCKROUTE8;
extern NSString* GIMMIE_EVENTID_UNLOCKROUTE9;
extern NSString* GIMMIE_EVENTID_UNLOCKROUTE10;
extern NSString* GIMMIE_EVENTID_30COINSTO500;
extern NSString* GIMMIE_EVENTID_NEWHIGHSCORE;

extern NSString* GIMMIE_EVENT_RP_PLAY3JOURNEYS;
extern NSString* GIMMIE_EVENT_RP_PLAYWITHFRIENDS;
extern NSString* GIMMIE_EVENT_RP_30COINSTO500;
extern NSString* GIMMIE_EVENT_RP_NEWHIGHSCORE;